### ISSUE TITLE
Crontab error runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by arvinpaundra** [mileusna/crontab#15]
Can you explain why the crontab logging that? i have no idea why the crontab keep logging kind of that stuff. I saw when crontab execute run(), it defer a function that recover the program with log like "Crontab error runtime error: invalid memory address or nil pointer dereference". thanks in advance.

**Comment by mileusna** [comment]
Hello,

I believe there is some issue with your function and params you are providing to the functions with crontab. You might provide some variable or pointer as a param to the crontab function, but that variable is de-referenced at the time of cron execution.

The code that replicate this panic would help of course.

**Comment by arvinpaundra** [comment]
thanks for your answer,

in my function i have no params btw, can u provide me other mistake that make that error happen?

**Comment by arvinpaundra** [comment]
i am not using my laptop at this moment, maybe i do it later to provide my code.

**Comment by mileusna** [comment]
Do you check errors with AddJob or use MustAddJob?
