### ISSUE TITLE
Type mismatch between interface and their implementation

### ISSUE THREAD

**Issue by tappoz** [mileusna/crontab#5]
Given this main file:

```go
package main

import (
	"log"

	"<PATH_TO>/foostuff"
	"github.com/mileusna/crontab"
)

func fooFunc(foo foostuff.Foo) {
	log.Println(foo.Bar())
}

func main() {
	ctab := crontab.New()

	fooStuff := foostuff.NewFoo()

	ctab.MustAddJob("* * * * *", fooFunc, fooStuff)
}

```

And this `foostuff` package:

```go
package foostuff

import "fmt"

type foo struct {
	fooFoo int
}

type Foo interface {
	Bar() string
}

func NewFoo() Foo {
	return &foo{
		fooFoo: 42,
	}
}

func (f *foo) Bar() string {
	return fmt.Sprintf("foo: %v", f.fooFoo)
}
```

Then when executing the main file I get this `panic` error message:

```
panic: Param with index 0 shold be `foostuff.Foo` not `*foostuff.foo`

goroutine 1 [running]:
github.com/mileusna/crontab.(*Crontab).MustAddJob(0xc420014540, 0x510ffe, 0x9, 0x4e9380, 0x518388, 0xc42000e3c0, 0x1, 0x1)
	<GOPATH>/src/github.com/mileusna/crontab/crontab.go:130 +0xae
main.main()
	<GOPATH>/src/<PATH_TO_MAIN>/main.go:19 +0xf5
exit status 2
```

I can see around line `crontab.go:106` there's a check via reflection about the input types for the function to be executed, but I think returning a `struct` compliant with the `interface` is supposed to be fine. 

Is this intended behavior? Is there a work around?
Thanks

**Comment by mileusna** [comment]
I see... Never test that case. :) Yes, from developers point of view, you should be able to pass that type to interface param, but it doesn't pass that lines of my code where types are compared.

I will take a look to see is there anything I can do when checking interface params. It also doesn't work with interface{} type as well.

**Comment by mileusna** [comment]
I believe I have found the easy way to fix it, I just need some more testing to do.

**Comment by tappoz** [comment]
Meanwhile I changed line 89 of `crontab.go` (`if t1 != t2 {`) to perform some more checks if it could help:

`if t1 != t2 && !t2.AssignableTo(t1) && !t2.ConvertibleTo(t1) {`

**Comment by mileusna** [comment]
Yes that is exactly what I'm doing right now :) although I believe that only `if !t2.AssignableTo(t1)` is enough, but as I said I will make some more test cases before updating package.

Sorry for not being able to respond sooner, I was on holidays.

**Comment by wuleninja** [comment]
Hi guys ! 
Thanks @mileusna for this very useful package !
I've come across the same issue as @tappoz, so I've made a change in a fork, and proposed it in a [PR](https://github.com/mileusna/crontab/pull/7).
However, I only needed this in my case:

```go
if t1 != t2 && !t2.Implements(t1)
```

Doesn't it also answer your issue, @tappoz ?

**Comment by mileusna** [comment]
I wanted to merge this, but this code breaks test with panic since non-interface types can't be passed to Implements() function while checking.

> panic: reflect: non-interface type passed to Type.Implements [recovered]
> panic: reflect: non-interface type passed to Type.Implements

**Comment by mileusna** [comment]
This is the final version I decided to go with, it won't panic and it will also return proper error:

```go
if t1 != t2 {
    if t1.Kind() != reflect.Interface {
        return fmt.Errorf("Param with index %d shold be `%s` not `%s`", i, t1, t2)
    }
    if !t2.Implements(t1) {
        return fmt.Errorf("Param with index %d of type `%s` doesn't implement interface `%s`", i, t2, t1)
    }
}
```

Thank you both from contributing. 👍

**Comment by wuleninja** [comment]
Yep, I've also come across this, by putting bad arguments by mistake. 
But I've never seen this in the tests since I cannot have the tests working:

```go
-> % go test
# github.com/ninjawule/crontab_test
./job_test.go:50:10: undefined: crontab.Fake
FAIL	github.com/ninjawule/crontab [build failed]
```

It seems you found the right solution !

**Comment by mileusna** [comment]
Maybe you have changed the name of the package. ```Fake()``` is implemented in ```crontab_test.go``` file which is the part of ```crontab``` package, unlike  ```job_test.go``` which is ```crontab_test```  package and tests package externally.

Putting functions in _test.go files but in original package will make them available while testing, but they won't be accessible to developers. It is a nice way to implement helper functions and to export some internal stuff for testing.

**Comment by wuleninja** [comment]
I dit change a package name once, but I rolled it back.
If you check all the changes I've made so far in the [fork](https://github.com/ninjawule/crontab/commits/latest), there is no change of package name.
I think it comes from the fact that, within a fork, there is sometimes no access to code put into `_test.go` files from the original repo.
